import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  shado: {
    shadowColor: '#2B1B17',
    elevation: 10,
  },

  scrollView: {
    // flex: 1,
  },

  logoutButtonBody: {
    padding: 10,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
  },
  ProfileBody: {
    flex: 1,
    flexDirection: 'row',
  },
  imageProfileBody: {
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  imageProfile: {
    height: 40,
    width: 40,
    // alignItems: 'center',
  },
  nameText: {
    fontSize: 20,
    marginTop: 10,
    fontWeight: '900',
  },
  logoutButton: {
    backgroundColor: '#ff8080',
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: 100,
    borderRadius: 10,
  },
  logoutButtonText: {
    fontSize: 20,
    fontWeight: '900',
  },
  ProfileContnenBody: {
    flex: 1,
    backgroundColor: '#fff',
    margin: 10,
    shadowColor: '#2B1B17',
    elevation: 30,
    height: 700,
    borderRadius: 15,
    padding: 10,
  },
  profilesImageBody: {
    // flex: 1,
    marginLeft: 140,
    marginRight: 10,
    margin: 5,
    marginTop: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 20,
    backgroundColor: '#fff',
    flexDirection: 'row',
    width: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilesImageSet: {
    height: 60,
    width: 60,
    backgroundColor: '#C0C0C0',
    borderRadius: 100,
    padding: 4,
  },
  inputContnenar: {
    // backgroundColor: '#d9d9d9',
    height: 70,
    marginBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 10,
  },
  inputText: {
    height: 40,
    borderBottomWidth: 2,
    borderColor: '#000',
    backgroundColor: '#fff',
    // borderRadius: 10,
    fontSize: 17,
    // paddingLeft: 10,
  },
  centeredTodoView: {
    flex: 1,
    backgroundColor: '#fff',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 200,
    borderTopWidth: 5,
    borderTopColor: '#000',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalTodoView: {
    padding: 10,
  },
  addButton: {
    width: 150,
    borderRadius: 10,
    height: 30,
    justifyContent: 'center',
  },
  buttonClose: {
    backgroundColor: '#ff8080',
  },
  textStyle: {
    fontSize: 20,
    color: '#000',
    fontWeight: '500',
    textAlign: 'center',
  },
});
